=== Ramblurr/supermarket_scrapy/schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "title": "Product set",
    "type": "array",
    "items": {
        "title": "Product",
        "type": "object",
        "properties": {
            "name": {
                "description": "The name of the product (required)",
                "type": "string"
            },
            "brand": {
                "description": "The brand of a product (optional)",
                "type": "string"
            },
            "producer": {
                "description": "The producing company (optional)",
                "type": "string"
            },
            "category": {
                "description": "The producing company (optional)",
                "type": "string"
            },
            "store": {
                "description": "The store (optional)",
                "type": "string"
            },
            "gtin": {
                "description": "The Global Trade Item Number (optional)",
                "type": "string"
            },
            "labels": {
                "type": "array",
                "items": {
                    "type": "string"
                },
                "uniqueItems": true
            },
            "ingredients": {
                "type": "array",
                "items": {
                    "anyOf": [
                        { "type": "string"},
                        {
                            "type": "object",
                            "properties": {
                                "name": {"type": "string"},
                                "resource": {"type": "string"}
                            },
                            "required": ["name", "resource"]
                        }
                    ]
                },
                "uniqueItems": true
            }
        },
        "required": ["name"]
    }
}

=== Ramblurr/supermarket_scrapy/testdata.json
[
   {
     "name": "My Product",
     "brand": "My Brand",
     "store": "My Store",
     "producer": "My Producer",
     "labels": [
       "BEPI",
       "BSCI"
     ],
     "ingredients": [
       "Milk",
       {
         "name": "Cacoa butter",
         "resource": "Cacoa"
       }
     ]
   },
   {
     "name": "Another Product",
     "brand": "My second Brand",
     "store": "My Store",
     "producer": "My Producer",
     "labels": [
       "Fair Trade"
     ],
     "ingredients": [
       {
         "name": "Silk",
         "resource": "Silk"
       }
     ]
   }
]
